### ISSUE TITLE
Support Image Opacity

### ISSUE THREAD

**Issue by vednig** [AST07/tkinterwidgets#1]
Code:

``` Python
trans_label=tkw.Label(root,image='image.png',opacity=0.5)
```

**Comment by vednig** [comment]
Also is there any way to change font or size in Label?

**Comment by astqx** [comment]
Hello, sorry for the late reply. 

Images are supported. There is an error in the code provided by you.

There are 2 main methods of displaying images in a `Label`,

* `tkinter.PhotoImage` (simple)

  ```
  img = tk.PhotoImage(file='image.png')
  ```

* [`PIL`](https://pillow.readthedocs.io/en/stable/reference/index.html) (recommended, as it gives more flexibility)

  ```
  from PIL import Image, ImageTk
  img = Image.open('image.png')
  img = ImageTk.PhotoImage(img)
  ```

And use this with the `Label` widget

```
label=tk.Label(root, image=img)
trans_label=tkw.Label(root, image=img, opacity=0.5)
```

Here's a working example 

```
from tkinter import *
import tkinterwidgets as tkw 
from PIL import ImageTk, Image

root=Tk()
root.config(bg='yellow')

img=Image.open('image.png')
img=img.resize((100,100))
img=ImageTk.PhotoImage(img)

label=Label(root,text='label')
label.pack()

trans_label=tkw.Label(root,image=img,opacity=0.5)
trans_label.image=img
trans_label.pack(pady=10)

root.mainloop()
```
***
[Reference](https://anzeljg.github.io/rin2/book2/2405/docs/tkinter/images.html)

**Comment by astqx** [comment]
Yes, there is, please refer to the documentation of the [`Label`](https://anzeljg.github.io/rin2/book2/2405/docs/tkinter/label.html) widget, it has all the information you need, including what I mentioned above.

**Comment by vednig** [comment]
And can we have more transparent components like canvas, frames, and buttons?

**Comment by vednig** [comment]
Should I open a new issue for this?

> And can we have more transparent components like canvas, frames, and buttons?

**Comment by vednig** [comment]
I was working on adding transparent background support to rounded buttons in [CustomTkinter](https://github.com/TomSchimansky/CustomTkinter) module. 
It would be a great help.🤗

**Comment by astqx** [comment]
> And can we have more transparent components like canvas, frames, and buttons?

That's a great idea, I created a more general transparent container, any widget inside it will follow the transparency and opacity rules of the container. It's in the [`dev`](https://github.com/AST07/tkinterwidgets/tree/dev) branch, I still need to do some testing, if it works perfectly then it would be able to support any component.
